import requests
from bs4 import BeautifulSoup
import json

empire_site = requests.get(url="https://www.empireonline.com/movies/features/best-movies-2/").text
soup = BeautifulSoup(empire_site, "html.parser")

# The site has dynamic html generated by JS. So, we get that JS first
all_js = soup.find(name="script", id="__NEXT_DATA__").string
# We convert the JS to a dictionary
x = json.loads(all_js)

# From the dictionary, we extract the list of items that we need
all_layouts = x['props']['pageProps']['data']['getArticleByFurl']['_layout']

# From the list of items, we get those which have the 'images' key and where it is not of NoneType or with value None
all_movies = [item['content']['images'] for item in all_layouts if
              item['content']['images'] is not None and item['content']['images'] != "None"][0]

# From the list of dictionaries of movies, we get just the titles
movie_titles = [movie.get('titleText') for movie in all_movies]

# The rank 1 movie does not have 1) before the title, so we have to remove the ")" for those which have it
movie_titles = [movie.split(")")[1].strip() if ")" in movie else movie for movie in movie_titles]

# As the page ranked movies from 100 to 1, we need to reverse our list now, to get movies in order
# from rank 1 till 100
movie_titles.reverse()

# Print the list of 100 greatest movies, and store in a file
print(movie_titles)
with open("100-top-movies.txt", "w") as file:
    for i in range(0, 100):
        file.write(f"{i + 1}) {movie_titles[i]}\n")
